server:
  port: 8080

spring:
  security:
    user:
      name: username
      password: password
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

logging:
  level:
    root: INFO
    ivolapuma.miniautorizador: DEBUG

miniautorizador:
  cartao:
    saldo-default: 500.0
